version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: django_backend
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: health_db  # Updated to use the new database
      DB_USER: jparep
      DB_PASSWORD: jparepson1@2
      PYTHONUNBUFFERED: 1
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: jparep
      POSTGRES_PASSWORD: jparepson1@2
      POSTGRES_DB: health_db  # Create the database during initialization
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Add initialization scripts
    ports:
      - "5432:5432"

volumes:
  postgres_data:
