version: '3.8'

services:
  # Django Backend Service
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile  # Corrected path to Dockerfile
    container_name: django_backend
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dev_db
      DB_USER: dev_user
      DB_PASSWORD: dev_password
      PYTHONUNBUFFERED: 1
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Frontend Service (Tailwind, React, etc.)
  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile  # Optional if the frontend also has its Dockerfile in deployment
    container_name: frontend_service
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: ["npm", "start"]

volumes:
  postgres_data:
