version: '3.8'

services:
  backend:
    build:
      context: ../backend
    container_name: django_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASSWORD=dev_password
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../frontend
    container_name: frontend_service
    ports:
      - "3000:3000"

volumes:
  postgres_data:
