version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: django_backend
    env_file: ../.env  # Load environment variables from .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: 1
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    env_file: ../.env  # Load environment variables for database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
