version: '3.8'

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
